
module.exports = [
    {short:"  " , name:"Please select a state"},
    {short:"AL" , name:"ALABAMA"},
	{short:"AK" , name:"ALASKA"},
	{short:"AS" , name:"AMERICAN SAMOA"},
	{short:"AZ" , name:"ARIZONA"},
	{short:"AR" , name:"ARKANSAS"},
	{short:"CA" , name:"CALIFORNIA"},
	{short:"CO" , name:"COLORADO"},
	{short:"CT" , name:"CONNECTICUT"},
	{short:"DE" , name:"DELAWARE"},
	{short:"DC" , name:"DISTRICT OF COLUMBIA"},
	{short:"FM" , name:"FEDERATED STATES OF MICRONESIA"},
	{short:"FL" , name:"FLORIDA"},
	{short:"GA" , name:"GEORGIA"},
	{short:"GU" , name:"GUAM GU"},
	{short:"HI" , name:"HAWAII"},
	{short:"ID" , name:"IDAHO"},
	{short:"IL" , name:"ILLINOIS"},
	{short:"IN" , name:"INDIANA"},
	{short:"IA" , name:"IOWA"},
	{short:"KS" , name:"KANSAS"},
	{short:"KY" , name:"KENTUCKY"},
	{short:"LA" , name:"LOUISIANA"},
	{short:"ME" , name:"MAINE"},
	{short:"MH" , name:"MARSHALL ISLANDS"},
	{short:"MD" , name:"MARYLAND"},
	{short:"MA" , name:"MASSACHUSETTS"},
	{short:"MI" , name:"MICHIGAN"},
	{short:"MN" , name:"MINNESOTA"},
	{short:"MS" , name:"MISSISSIPPI"},
	{short:"MO" , name:"MISSOURI"},
	{short:"MT" , name:"MONTANA"},
	{short:"NE" , name:"NEBRASKA"},
	{short:"NV" , name:"NEVADA"},
	{short:"NH" , name:"NEW HAMPSHIRE"},
	{short:"NJ" , name:"NEW JERSEY"},
	{short:"NM" , name:"NEW MEXICO"},
	{short:"NY" , name:"NEW YORK"},
	{short:"NC" , name:"NORTH CAROLINA"},
	{short:"ND" , name:"NORTH DAKOTA"},
	{short:"MP" , name:"NORTHERN MARIANA ISLANDS"},
	{short:"OH" , name:"OHIO"},
	{short:"OK" , name:"OKLAHOMA"},
	{short:"OR" , name:"OREGON"},
	{short:"PW" , name:"PALAU"},
	{short:"PA" , name:"PENNSYLVANIA"},
	{short:"PR" , name:"PUERTO RICO"},
	{short:"RI" , name:"RHODE ISLAND"},
	{short:"SC" , name:"SOUTH CAROLINA"},
	{short:"SD" , name:"SOUTH DAKOTA"},
	{short:"TN" , name:"TENNESSEE"},
	{short:"TX" , name:"TEXAS"},
	{short:"UT" , name:"UTAH"},
	{short:"VT" , name:"VERMONT"},
	{short:"VI" , name:"VIRGIN ISLANDS"},
	{short:"VA" , name:"VIRGINIA"},
	{short:"WA" , name:"WASHINGTON"},
	{short:"WV" , name:"WEST VIRGINIA"},
	{short:"WI" , name:"WISCONSIN"},
	{short:"WY" , name:"WYOMING"}
]